version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: db_container228
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    env_file:
      - dbLocal.yaml

volumes:
  postgres_data: